@startuml logicalArchitecture
skinparam linetype polyline
skinparam ranksep 10
skinparam nodesep 20
skinparam classBackgroundColor WhiteSmoke
skinparam classBorderColor DarkSlateGrey
skinparam ArrowColor Black
hide members
hide circles

package Controller{
    class "Database Controller"
    class "App Controller"
}
package Model{
    class "Bubble Model"    
    class "Comments Model"
    class "Like & Dislike Model"
}
package View{
    class "Bubble View"
    class "Create Bubble Page"
}

Controller -[hidden]->Model
Model <.up.> Controller : Update data
Controller .right.> View : Data to be sent

@enduml