@startuml logicalArchitecture
skinparam linetype polyline
skinparam ranksep 10
skinparam nodesep 20
skinparam componentBackgroundColor WhiteSmoke
skinparam componentBorderColor DarkSlateGrey
skinparam componentFontColor Black
skinparam ArrowColor Black
hide members
hide circles

package Controller{
    component "Database Controller"
    component "App Controller"
}
package Model{
    component "Bubble Model"    
    component "Comments Model"
    component "Like & Dislike Model"
}
package View{
    component "Bubble View"
    component "Bubble Creation View"
    component "Comment View"
    component "Comment Creation View"
}

View -[hidden]->Controller
Controller -[hidden]->Model
Model <.. Controller : Changes data stored
Controller .left.> View : Changes components seen by user

@enduml