@startuml physicalArchitecture
scale 200
skinparam linetype polyline
skinparam componentBackgroundColor WhiteSmoke
skinparam componentBorderColor DarkSlateGrey
skinparam componentFontColor Black

skinparam interfaceBackgroundColor WhiteSmoke
skinparam interfaceBorderColor DarkSlateGrey
skinparam interfaceFontColor Black

skinparam ArrowColor Black

left to right direction

node "Database Server" as database <<device>>{
  [Firebase API] <<component>> as firebaseApi
  Interface " " as int1
}

node "Client" as client <<device>> {
  component "RetrospectiveWall" as maincomp <<component>>
}

client -[hidden]up-> database

firebaseApi -down- int1
int1 <.down. maincomp



@enduml