@startuml physicalArchitecture
scale 200
skinparam linetype polyline
skinparam componentBackgroundColor WhiteSmoke
skinparam componentBorderColor DarkSlateGrey
skinparam componentFontColor Black

skinparam interfaceBackgroundColor WhiteSmoke
skinparam interfaceBorderColor DarkSlateGrey
skinparam interfaceFontColor Black

skinparam ArrowColor Black

left to right direction

node "Database Server" as database <<device>>{
  [Firebase API] <<component>> as firebaseApi
  [Firebase Database] <<component>> as firebaseDb
  Interface " " as int1
}

node "Client" as client <<device>> {
  component Flutter as app <<framework>>
  component "Bubble" as dp <<component>>
  component "Login & Signup" as login <<component>>
  component "FlutterFire" as flutterfire <<library>>
}

client -[hidden]up-> database

firebaseApi -down- int1
int1 <.down. flutterfire

firebaseApi <- firebaseDb

flutterfire <.down. dp
flutterfire <.down. login

@enduml